apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-jkube
spec:
  workspaces:
  - name: maven-repo
    description: The .m2 repo volume
  - name: source
    description: The workspace consisting of maven project.
  - name: maven-settings
    description: >-
      The workspace consisting of the custom maven settings
      provided by the user.  
  params:
  - name: MAVEN_SERVER_URL
    description: Nexus repo URL
    type: string
  - name: MAVEN_PROJECT_CONTEXT_DIR
    description: Project/Module directory
    type: string
    default: "."
  - name: GOALS
    description: The Maven goals to run
    type: string
    default: "clean package"
  steps:
    - name: mvn-jkube
      image: quay.io/rafaeltuelho/mvn-kube-oc:openjdk-11
      workingDir: /workspace/source
      script: | 
        echo "Deploy to OCP using jKube maven plugin"
        mvn $(inputs.params.GOALS) -e -P openshift -f "$(inputs.params.MAVEN_PROJECT_CONTEXT_DIR)" -s $(workspaces.maven-settings.path)/settings.xml -Dmaven.repo.local=$(workspaces.maven-repo.path)
      env:
        - name: MAVEN_SERVER_URL
          value: "$(inputs.params.MAVEN_SERVER_URL)"
        - name: MAVEN_OPTS
          value: "-Xms1024m -Xmx2048m -XX:+ExitOnOutOfMemoryError"          